#!/usr/bin/env bash

set -exfu

# initialize /nix
if [[ -d /nix-install ]]; then
    if [[ ! -d /nix/var/nix/profiles/per-user/ubuntu/profile/. ]]; then
        rsync -ia /nix-install/. /nix/.
    else
        rsync -ia /nix-install/store/. /nix/store/.
    fi
fi

set +x; . /home/ubuntu/.nix-profile/etc/profile.d/nix.sh; set -x
if [[ ! -f ~/.nix-profile/share/nix-direnv/direnvrc ]]; then
    nix profile install nixpkgs#nix-direnv
fi

# initial flake from /app
cd /app
eval "$(direnv hook bash)"
touch flake.nix
direnv allow
_direnv_hook

# one of the nix stores has an executable "nix-entrypoint"
exec "nix-entrypoint" "$@"
